FROM node:18-slim

WORKDIR /app

# Instalar Docker CLI para poder ejecutar contenedores desde dentro del backend
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* get-docker.sh

COPY backend/package*.json ./

RUN npm install

COPY backend/. .

EXPOSE 3000

CMD ["node", "server.js"]